import type {
  Agent,
  AppState,
  Automation,
  Campaign,
  Carrier,
  Conversation,
  Integration,
  Order,
  Product,
} from "./types";
import { hoursAgo, minutesAgo, uid } from "./format";

export const WORKSPACE = {
  name: "Atlas Atelier",
  plan: "Growth",
  country: "Morocco",
  currency: "MAD",
};

const products: Product[] = [
  { id: "p1", sku: "AUR-SHT-BGE", name: "Aurora Linen Shirt", variant: "Beige · M", price: 289, stock: 42, category: "Shirts", imageHue: 32 },
  { id: "p2", sku: "TER-KNT-OLV", name: "Terra Knit Polo", variant: "Olive · L", price: 349, stock: 18, category: "Knitwear", imageHue: 92 },
  { id: "p3", sku: "NOM-DNM-IND", name: "Nomad Denim", variant: "Indigo · 32", price: 419, stock: 27, category: "Denim", imageHue: 220 },
  { id: "p4", sku: "MRK-LOF-TAN", name: "Marrakech Loafers", variant: "Tan · 42", price: 459, stock: 11, category: "Shoes", imageHue: 28 },
  { id: "p5", sku: "SAH-DRS-CRM", name: "Sahara Slip Dress", variant: "Cream · S", price: 389, stock: 15, category: "Dresses", imageHue: 40 },
  { id: "p6", sku: "ATL-BLZ-NVY", name: "Atlas Linen Blazer", variant: "Navy · M", price: 629, stock: 8, category: "Outerwear", imageHue: 230 },
  { id: "p7", sku: "CAS-TEE-WHT", name: "Casa Cotton Tee", variant: "White · L", price: 149, stock: 84, category: "Basics", imageHue: 0 },
  { id: "p8", sku: "RIF-BAG-SND", name: "Rif Canvas Tote", variant: "Sand", price: 219, stock: 33, category: "Bags", imageHue: 38 },
];

export const agents: Agent[] = [
  { id: "a1", name: "Yasmine El Fassi", role: "confirmation", email: "yasmine@atlasatelier.ma", initials: "YE", online: true, confirmedToday: 31, avgConfirmMin: 4, hue: 160 },
  { id: "a2", name: "Karim Bennani", role: "confirmation", email: "karim@atlasatelier.ma", initials: "KB", online: true, confirmedToday: 24, avgConfirmMin: 6, hue: 200 },
  { id: "a3", name: "Salma Idrissi", role: "inbox", email: "salma@atlasatelier.ma", initials: "SI", online: true, confirmedToday: 9, avgConfirmMin: 8, hue: 280 },
  { id: "a4", name: "Omar Cherkaoui", role: "shipping", email: "omar@atlasatelier.ma", initials: "OC", online: true, confirmedToday: 0, avgConfirmMin: 0, hue: 30 },
  { id: "a5", name: "Nour Alami", role: "returns", email: "nour@atlasatelier.ma", initials: "NA", online: false, confirmedToday: 3, avgConfirmMin: 12, hue: 350 },
  { id: "a6", name: "Amine Kadiri", role: "owner", email: "amine@atlasatelier.ma", initials: "AK", online: true, confirmedToday: 6, avgConfirmMin: 5, hue: 150 },
];

export const carriers: Carrier[] = [
  { id: "c1", name: "Ozon Express", connected: true, pickupWindow: "Today 17:00", cities: ["Casablanca", "Rabat", "Marrakech", "Kenitra"], deliveredRate: 91, avgDays: 2.1 },
  { id: "c2", name: "Ameex", connected: true, pickupWindow: "Today 16:30", cities: ["Casablanca", "Tangier", "Fes", "Meknes"], deliveredRate: 88, avgDays: 2.4 },
  { id: "c3", name: "Cathedis", connected: true, pickupWindow: "Tomorrow 10:00", cities: ["Marrakech", "Agadir", "Essaouira"], deliveredRate: 86, avgDays: 2.8 },
  { id: "c4", name: "Sendit", connected: false, pickupWindow: "—", cities: ["Nationwide"], deliveredRate: 84, avgDays: 3.0 },
  { id: "c5", name: "Aramex", connected: true, pickupWindow: "Today 18:00", cities: ["Casablanca", "Rabat", "Tangier"], deliveredRate: 93, avgDays: 1.9 },
  { id: "c6", name: "Digylog", connected: false, pickupWindow: "—", cities: ["Casablanca", "Mohammedia"], deliveredRate: 82, avgDays: 3.2 },
];

const customers = [
  { id: "cu1", name: "Nabil Amrani", phone: "+212 6 12 34 56 78", city: "Marrakech", address: "12 Rue Ibn Toumert, Gueliz" },
  { id: "cu2", name: "Ihsane Mernissi", phone: "+212 6 61 22 01 14", city: "Casablanca", address: "8 Bd Anfa, Maarif" },
  { id: "cu3", name: "Tarik Ouazzani", phone: "+212 6 54 98 11 20", city: "Rabat", address: "4 Av. Hassan II, Agdal" },
  { id: "cu4", name: "Nadia Harmouch", phone: "+212 6 77 43 09 12", city: "Tangier", address: "21 Rue de la Plage" },
  { id: "cu5", name: "Mounir Zahraoui", phone: "+212 6 18 90 44 33", city: "Agadir", address: "Talborjt, Rue 14" },
  { id: "cu6", name: "Dounia Slaoui", phone: "+212 6 25 71 88 09", city: "Fes", address: "Ville Nouvelle, Av. des FAR" },
  { id: "cu7", name: "Yassine Berrada", phone: "+212 6 33 12 67 45", city: "Casablanca", address: "Hay Hassani, Bloc 9" },
  { id: "cu8", name: "Noura Senhaji", phone: "+212 6 41 55 02 18", city: "Kenitra", address: "Maamora, Rue 7" },
  { id: "cu9", name: "Hicham Lahlou", phone: "+212 6 09 88 31 74", city: "Oujda", address: "Bd Mohammed V" },
  { id: "cu10", name: "Sara Benjelloun", phone: "+212 6 72 14 60 05", city: "Rabat", address: "Hay Riad, Sect 6" },
  { id: "cu11", name: "Anas Tazi", phone: "+212 6 58 27 19 40", city: "Meknes", address: "Hamria, Rue Accra" },
  { id: "cu12", name: "Lina Chraibi", phone: "+212 6 14 03 88 21", city: "Marrakech", address: "Hivernage, Rue Echouhada" },
  { id: "cu13", name: "Reda Fassi", phone: "+212 6 99 41 12 08", city: "Casablanca", address: "Ain Diab, Résidence Palmier" },
  { id: "cu14", name: "Amina Kettani", phone: "+212 6 21 66 70 53", city: "Tetouan", address: "M'diq road, n°44" },
  { id: "cu15", name: "Omar Squalli", phone: "+212 6 80 19 35 62", city: "Casablanca", address: "Sidi Belyout, 3 Rue Allal" },
];

function item(productId: string, qty = 1) {
  const p = products.find((x) => x.id === productId)!;
  return { productId, name: p.name, variant: p.variant, qty, price: p.price };
}

function order({
  hours,
  events,
  ...rest
}: Omit<Order, "id" | "timeline" | "total" | "createdAt"> & {
  hours: number;
  events: Order["timeline"];
}): Order {
  const total = rest.items.reduce((s, i) => s + i.price * i.qty, 0);
  return {
    ...rest,
    id: uid("ord"),
    total,
    createdAt: hoursAgo(hours),
    timeline: events.map((e, i) => ({
      ...e,
      id: uid("ev"),
      at: hoursAgo(Math.max(0, hours - i * 0.4)),
    })),
  };
}

const orders: Order[] = [
  order({
    number: "NX-11546",
    hours: 0.12,
    customer: customers[0],
    items: [item("p1")],
    payment: "cod",
    status: "pending_confirmation",
    source: "shopify",
    assignedTo: "a1",
    events: [
      { id: "", at: "", title: "Order placed", detail: "Shopify · COD 289 MAD", tone: "default" },
      { id: "", at: "", title: "WhatsApp sent", detail: "Confirmation template delivered", tone: "default" },
    ],
  }),
  order({
    number: "NX-11545",
    hours: 0.4,
    customer: customers[1],
    items: [item("p2"), item("p7")],
    payment: "prepaid",
    status: "confirmed",
    source: "shopify",
    assignedTo: "a1",
    confirmationChannel: "whatsapp",
    events: [
      { id: "", at: "", title: "Order placed", detail: "Shopify · Prepaid", tone: "default" },
      { id: "", at: "", title: "Customer confirmed", detail: "WhatsApp · 48s", tone: "success" },
    ],
  }),
  order({
    number: "NX-11544",
    hours: 0.8,
    customer: customers[2],
    items: [item("p3")],
    payment: "cod",
    status: "confirmed",
    source: "woocommerce",
    assignedTo: "a2",
    confirmationChannel: "call",
    events: [
      { id: "", at: "", title: "Order placed", tone: "default" },
      { id: "", at: "", title: "Confirmed by call", detail: "Karim · 3m 12s", tone: "success" },
    ],
  }),
  order({
    number: "NX-11543",
    hours: 1.2,
    customer: customers[3],
    items: [item("p4")],
    payment: "cod",
    status: "pending_confirmation",
    source: "youcan",
    assignedTo: "a2",
    events: [
      { id: "", at: "", title: "Order placed", detail: "YouCan", tone: "default" },
      { id: "", at: "", title: "No reply yet", detail: "Follow-up scheduled in 20m", tone: "warn" },
    ],
  }),
  order({
    number: "NX-11542",
    hours: 1.6,
    customer: customers[4],
    items: [item("p5")],
    payment: "cod",
    status: "packed",
    source: "facebook",
    assignedTo: "a1",
    confirmationChannel: "whatsapp",
    carrierId: "c3",
    events: [
      { id: "", at: "", title: "Confirmed via WhatsApp", tone: "success" },
      { id: "", at: "", title: "Packed", detail: "Warehouse Casablanca", tone: "default" },
    ],
  }),
  order({
    number: "NX-11541",
    hours: 2.1,
    customer: customers[5],
    items: [item("p6")],
    payment: "cod",
    status: "pending_confirmation",
    source: "tiktok",
    assignedTo: "a1",
    events: [{ id: "", at: "", title: "Lead imported from TikTok Forms", tone: "default" }],
  }),
  order({
    number: "NX-11540",
    hours: 3,
    customer: customers[6],
    items: [item("p1"), item("p8")],
    payment: "cod",
    status: "shipped",
    source: "shopify",
    assignedTo: "a2",
    confirmationChannel: "ai",
    carrierId: "c1",
    awb: "OZ771042659CR12",
    events: [
      { id: "", at: "", title: "AI confirmed", detail: "Nexora Agent · 22s", tone: "success" },
      { id: "", at: "", title: "Dispatched", detail: "Ozon Express · AWB created", tone: "default" },
    ],
  }),
  order({
    number: "NX-11539",
    hours: 5,
    customer: customers[7],
    items: [item("p7", 2)],
    payment: "cod",
    status: "out_for_delivery",
    source: "woocommerce",
    assignedTo: "a1",
    confirmationChannel: "whatsapp",
    carrierId: "c2",
    awb: "AMX99021488",
    events: [
      { id: "", at: "", title: "Out for delivery", detail: "Driver: Hakim N.", tone: "default" },
    ],
  }),
  order({
    number: "NX-11538",
    hours: 8,
    customer: customers[8],
    items: [item("p2")],
    payment: "cod",
    status: "failed_delivery",
    source: "shopify",
    assignedTo: "a3",
    confirmationChannel: "call",
    carrierId: "c2",
    awb: "AMX99021001",
    events: [
      { id: "", at: "", title: "Delivery failed", detail: "Customer unreachable · attempt 1", tone: "danger" },
    ],
  }),
  order({
    number: "NX-11537",
    hours: 11,
    customer: customers[9],
    items: [item("p5"), item("p8")],
    payment: "prepaid",
    status: "delivered",
    source: "shopify",
    assignedTo: "a1",
    confirmationChannel: "whatsapp",
    carrierId: "c5",
    awb: "ARX4419022",
    events: [{ id: "", at: "", title: "Delivered", detail: "Signed by customer", tone: "success" }],
  }),
  order({
    number: "NX-11536",
    hours: 14,
    customer: customers[10],
    items: [item("p3")],
    payment: "cod",
    status: "delivered",
    source: "youcan",
    assignedTo: "a2",
    confirmationChannel: "whatsapp",
    carrierId: "c1",
    awb: "OZ771040112",
    events: [{ id: "", at: "", title: "COD collected · 419 MAD", tone: "success" }],
  }),
  order({
    number: "NX-11535",
    hours: 18,
    customer: customers[11],
    items: [item("p4")],
    payment: "cod",
    status: "rto",
    source: "facebook",
    assignedTo: "a5",
    confirmationChannel: "call",
    carrierId: "c3",
    awb: "CTD882190",
    rtoReason: "Customer refused — size",
    events: [{ id: "", at: "", title: "Returned to origin", detail: "Size issue", tone: "danger" }],
  }),
  order({
    number: "NX-11534",
    hours: 20,
    customer: customers[12],
    items: [item("p6")],
    payment: "cod",
    status: "returned",
    source: "shopify",
    assignedTo: "a5",
    carrierId: "c1",
    awb: "OZ771038001",
    rtoReason: "Not home after 2 attempts",
    events: [{ id: "", at: "", title: "Parcel back in warehouse", tone: "warn" }],
  }),
  order({
    number: "NX-11533",
    hours: 22,
    customer: customers[13],
    items: [item("p1")],
    payment: "cod",
    status: "cancelled",
    source: "tiktok",
    assignedTo: "a2",
    confirmationChannel: "whatsapp",
    events: [{ id: "", at: "", title: "Customer cancelled on WhatsApp", tone: "danger" }],
  }),
  order({
    number: "NX-11532",
    hours: 26,
    customer: customers[14],
    items: [item("p2"), item("p3")],
    payment: "cod",
    status: "exchanged",
    source: "shopify",
    assignedTo: "a5",
    confirmationChannel: "whatsapp",
    carrierId: "c5",
    awb: "ARX4418700",
    events: [{ id: "", at: "", title: "Exchange created", detail: "Olive L → Olive M", tone: "default" }],
  }),
  order({
    number: "NX-11531",
    hours: 4.2,
    customer: customers[0],
    items: [item("p8")],
    payment: "cod",
    status: "pending_confirmation",
    source: "sheets",
    assignedTo: "a3",
    events: [{ id: "", at: "", title: "Imported from Google Sheet", tone: "default" }],
  }),
  order({
    number: "NX-11530",
    hours: 6,
    customer: customers[2],
    items: [item("p7", 3)],
    payment: "prepaid",
    status: "shipped",
    source: "shopify",
    assignedTo: "a4",
    carrierId: "c5",
    awb: "ARX4419108",
    events: [{ id: "", at: "", title: "Shipped", detail: "Aramex", tone: "default" }],
  }),
  order({
    number: "NX-11529",
    hours: 7,
    customer: customers[6],
    items: [item("p5")],
    payment: "cod",
    status: "confirmed",
    source: "woocommerce",
    assignedTo: "a1",
    confirmationChannel: "whatsapp",
    events: [{ id: "", at: "", title: "Confirmed", tone: "success" }],
  }),
  order({
    number: "NX-11528",
    hours: 9,
    customer: customers[4],
    items: [item("p3")],
    payment: "cod",
    status: "new",
    source: "manual",
    events: [{ id: "", at: "", title: "Created manually by Omar", tone: "default" }],
  }),
  order({
    number: "NX-11527",
    hours: 12,
    customer: customers[10],
    items: [item("p1"), item("p7")],
    payment: "cod",
    status: "delivered",
    source: "youcan",
    assignedTo: "a2",
    confirmationChannel: "ai",
    carrierId: "c2",
    awb: "AMX99019880",
    events: [{ id: "", at: "", title: "Delivered · COD 438 MAD", tone: "success" }],
  }),
  order({
    number: "NX-11526",
    hours: 15,
    customer: customers[7],
    items: [item("p4")],
    payment: "cod",
    status: "out_for_delivery",
    source: "shopify",
    assignedTo: "a4",
    carrierId: "c1",
    awb: "OZ771039441",
    events: [{ id: "", at: "", title: "Out for delivery", tone: "default" }],
  }),
  order({
    number: "NX-11525",
    hours: 28,
    customer: customers[11],
    items: [item("p6")],
    payment: "prepaid",
    status: "delivered",
    source: "shopify",
    assignedTo: "a1",
    carrierId: "c5",
    awb: "ARX4418011",
    events: [{ id: "", at: "", title: "Delivered", tone: "success" }],
  }),
  order({
    number: "NX-11524",
    hours: 30,
    customer: customers[8],
    items: [item("p8"), item("p7")],
    payment: "cod",
    status: "rto",
    source: "facebook",
    assignedTo: "a5",
    carrierId: "c2",
    awb: "AMX99017660",
    rtoReason: "Wrong phone number",
    events: [{ id: "", at: "", title: "RTO — invalid phone", tone: "danger" }],
  }),
  order({
    number: "NX-11523",
    hours: 2.6,
    customer: customers[13],
    items: [item("p2")],
    payment: "cod",
    status: "pending_confirmation",
    source: "shopify",
    assignedTo: "a2",
    events: [{ id: "", at: "", title: "WhatsApp unread", tone: "warn" }],
  }),
  order({
    number: "NX-11522",
    hours: 0.05,
    customer: customers[12],
    items: [item("p1"), item("p4")],
    payment: "cod",
    status: "new",
    source: "shopify",
    events: [{ id: "", at: "", title: "Live order from Shopify", tone: "default" }],
  }),
];

const conversations: Conversation[] = [
  {
    id: "cv1",
    customerId: "cu1",
    customerName: "Nabil Amrani",
    phone: "+212 6 12 34 56 78",
    city: "Marrakech",
    channel: "whatsapp",
    unread: 1,
    lastMessage: "Confirm",
    lastAt: minutesAgo(8),
    orderId: orders.find((o) => o.number === "NX-11546")?.id,
    assignedTo: "a1",
    messages: [
      {
        id: "m1",
        at: minutesAgo(18),
        from: "system",
        text: "Hi Nabil, we received your order NX-11546\nAurora Linen Shirt · Beige — 289 MAD\nCash on delivery · Marrakech",
        buttons: ["Confirm", "Edit", "Cancel"],
      },
      { id: "m2", at: minutesAgo(8), from: "customer", text: "Confirm" },
    ],
  },
  {
    id: "cv2",
    customerId: "cu2",
    customerName: "Ihsane Mernissi",
    phone: "+212 6 61 22 01 14",
    city: "Casablanca",
    channel: "whatsapp",
    unread: 0,
    lastMessage: "Perfect, thank you!",
    lastAt: minutesAgo(25),
    orderId: orders.find((o) => o.number === "NX-11545")?.id,
    assignedTo: "a1",
    messages: [
      { id: "m3", at: minutesAgo(40), from: "ai", text: "Your Terra Knit Polo is confirmed. We’ll ship today via Ozon Express." },
      { id: "m4", at: minutesAgo(25), from: "customer", text: "Perfect, thank you!" },
    ],
  },
  {
    id: "cv3",
    customerId: "cu8",
    customerName: "Noura Senhaji",
    phone: "+212 6 41 55 02 18",
    city: "Kenitra",
    channel: "whatsapp",
    unread: 2,
    lastMessage: "The driver called but I was in a meeting",
    lastAt: minutesAgo(12),
    orderId: orders.find((o) => o.number === "NX-11539")?.id,
    assignedTo: "a3",
    messages: [
      { id: "m5", at: minutesAgo(80), from: "system", text: "Your order NX-11539 is out for delivery today. Driver: Hakim N. · +212 661 220 114" },
      { id: "m6", at: minutesAgo(12), from: "customer", text: "The driver called but I was in a meeting. Can he come after 18:00?" },
    ],
  },
  {
    id: "cv4",
    customerId: "cu6",
    customerName: "Dounia Slaoui",
    phone: "+212 6 25 71 88 09",
    city: "Fes",
    channel: "instagram",
    unread: 1,
    lastMessage: "Do you have this in black?",
    lastAt: minutesAgo(33),
    assignedTo: "a3",
    messages: [
      { id: "m7", at: minutesAgo(50), from: "customer", text: "Hi, I saw the Atlas Linen Blazer. Do you have this in black?" },
    ],
  },
  {
    id: "cv5",
    customerId: "cu4",
    customerName: "Nadia Harmouch",
    phone: "+212 6 77 43 09 12",
    city: "Tangier",
    channel: "whatsapp",
    unread: 0,
    lastMessage: "Still thinking",
    lastAt: minutesAgo(70),
    orderId: orders.find((o) => o.number === "NX-11543")?.id,
    assignedTo: "a2",
    messages: [
      { id: "m8", at: minutesAgo(90), from: "system", text: "Hi Nadia, confirm your Marrakech Loafers · 459 MAD COD to Tangier?", buttons: ["Confirm", "Cancel"] },
      { id: "m9", at: minutesAgo(70), from: "customer", text: "Still thinking, can I confirm tonight?" },
    ],
  },
  {
    id: "cv6",
    customerId: "cu11",
    customerName: "Lina Chraibi",
    phone: "+212 6 14 03 88 21",
    city: "Marrakech",
    channel: "whatsapp",
    unread: 0,
    lastMessage: "I’d like to exchange for a smaller size",
    lastAt: hoursAgo(18),
    orderId: orders.find((o) => o.number === "NX-11535")?.id,
    assignedTo: "a5",
    messages: [
      { id: "m10", at: hoursAgo(19), from: "customer", text: "The loafers are too big. I’d like to exchange for a smaller size." },
      { id: "m11", at: hoursAgo(18), from: "agent", text: "Of course Lina — we’ll turn the return into an exchange. Size 41 is in stock." },
    ],
  },
  {
    id: "cv7",
    customerId: "cu15",
    customerName: "Omar Squalli",
    phone: "+212 6 80 19 35 62",
    city: "Casablanca",
    channel: "email",
    unread: 0,
    lastMessage: "Invoice for NX-11532 please",
    lastAt: hoursAgo(20),
    assignedTo: "a3",
    messages: [
      { id: "m12", at: hoursAgo(20), from: "customer", text: "Invoice for NX-11532 please" },
      { id: "m13", at: hoursAgo(19.5), from: "agent", text: "Sent to your email. Merci Omar." },
    ],
  },
  {
    id: "cv8",
    customerId: "cu5",
    customerName: "Mounir Zahraoui",
    phone: "+212 6 18 90 44 33",
    city: "Agadir",
    channel: "whatsapp",
    unread: 1,
    lastMessage: "Is the dress machine washable?",
    lastAt: minutesAgo(4),
    orderId: orders.find((o) => o.number === "NX-11542")?.id,
    assignedTo: "a3",
    messages: [
      { id: "m14", at: minutesAgo(4), from: "customer", text: "Is the Sahara Slip Dress machine washable?" },
    ],
  },
];

const automations: Automation[] = [
  { id: "au1", name: "WhatsApp confirm on new order", enabled: true, trigger: "Order created", condition: "Payment is COD", action: "Send WhatsApp confirmation template", runsToday: 41 },
  { id: "au2", name: "Auto-dispatch confirmed COD", enabled: true, trigger: "Status = Confirmed", condition: "City in Ozon coverage", action: "Create Ozon Express shipment + add to today’s manifest", runsToday: 18 },
  { id: "au3", name: "Follow-up if no reply", enabled: true, trigger: "30 min after WhatsApp", condition: "Status still pending", action: "Send reminder · assign to confirmation agent", runsToday: 9 },
  { id: "au4", name: "Out for delivery ping", enabled: true, trigger: "Carrier webhook: OFD", condition: "Always", action: "WhatsApp with driver name + COD amount", runsToday: 14 },
  { id: "au5", name: "Failed attempt rescue", enabled: true, trigger: "Delivery failed", condition: "Attempt < 3", action: "WhatsApp reschedule buttons + call task", runsToday: 3 },
  { id: "au6", name: "Thank-you + review", enabled: false, trigger: "Delivered", condition: "Always", action: "Send thank-you + 10% next-order code", runsToday: 0 },
];

const campaigns: Campaign[] = [
  {
    id: "cp1",
    name: "Ramadan restock — linen shirts",
    status: "sent",
    audience: "Delivered customers · 90 days",
    sent: 1840,
    delivered: 1762,
    replied: 214,
    converted: 67,
    template: "Nabil, Aurora Linen is back in beige & olive. Reply SHIRT for 15% off tonight.",
  },
  {
    id: "cp2",
    name: "Cart recovery · Casa & Rabat",
    status: "scheduled",
    audience: "Unconfirmed COD · last 7 days",
    sent: 0,
    delivered: 0,
    replied: 0,
    converted: 0,
    scheduledAt: hoursAgo(-6),
    template: "Your order is still on hold. Reply 1 to confirm and we ship today.",
  },
  {
    id: "cp3",
    name: "VIP drop — Atlas blazer",
    status: "draft",
    audience: "AOV > 500 MAD",
    sent: 0,
    delivered: 0,
    replied: 0,
    converted: 0,
    template: "Early access: Atlas Linen Blazer. 40 pieces. Reply BLAZER to reserve.",
  },
];

const integrations: Integration[] = [
  { id: "i1", name: "Shopify", kind: "store", connected: true, detail: "atlas-atelier.myshopify.com · 312 orders synced" },
  { id: "i2", name: "WooCommerce", kind: "store", connected: true, detail: "shop.atlasatelier.ma · 88 orders synced" },
  { id: "i3", name: "YouCan", kind: "store", connected: true, detail: "Connected · 41 leads this week" },
  { id: "i4", name: "Google Sheets", kind: "sheet", connected: true, detail: "Orders_Master · last import 12m ago" },
  { id: "i5", name: "Facebook Lead Ads", kind: "ads", connected: true, detail: "2 forms · 19 leads today" },
  { id: "i6", name: "TikTok Forms", kind: "ads", connected: false, detail: "Connect to import Spark Ads leads" },
  { id: "i7", name: "WhatsApp Cloud API", kind: "channel", connected: true, detail: "+212 6 00 11 22 33 · green tick" },
  { id: "i8", name: "Instagram", kind: "channel", connected: true, detail: "@atlasatelier · DMs synced" },
  { id: "i9", name: "Ozon Express", kind: "carrier", connected: true, detail: "Contract rates · webhooks live" },
  { id: "i10", name: "Ameex", kind: "carrier", connected: true, detail: "Labels + COD remittance" },
  { id: "i11", name: "Aramex", kind: "carrier", connected: true, detail: "Pickup 18:00 Casa hub" },
  { id: "i12", name: "Cathedis", kind: "carrier", connected: true, detail: "South Morocco coverage" },
];

export function createSeedState(): AppState {
  return {
    orders,
    products,
    conversations,
    agents,
    carriers,
    automations,
    campaigns,
    integrations,
    manifests: [
      {
        id: "mf1",
        carrierId: "c1",
        createdAt: hoursAgo(1),
        orderIds: orders.filter((o) => o.carrierId === "c1" && (o.status === "shipped" || o.status === "out_for_delivery")).map((o) => o.id),
        pickupAt: "Today 17:00",
        status: "ready",
      },
    ],
    ai: {
      enabled: true,
      name: "Noor",
      languages: ["French", "Arabic", "English", "Darija"],
      tone: "Warm, concise, sales-aware",
      canConfirm: true,
      canCancel: false,
      canUpsell: true,
      knowledge:
        "Atlas Atelier sells contemporary Moroccan fashion. COD is available nationwide. Free exchanges within 7 days. Confirmation hours 9:00–22:00. Warehouse in Casablanca.",
    },
  };
}
